# Generated by Django 3.2.6 on 2021-09-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profiller'},
        ),
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
