# Generated by Django 3.2.6 on 2021-09-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210917_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaj',
            old_name='recipient',
            new_name='alici',
        ),
        migrations.RenameField(
            model_name='mesaj',
            old_name='sender',
            new_name='gonderen',
        ),
        migrations.RenameField(
            model_name='mesaj',
            old_name='body',
            new_name='mesaj',
        ),
        migrations.RenameField(
            model_name='mesaj',
            old_name='is_read',
            new_name='okundu',
        ),
        migrations.RenameField(
            model_name='mesaj',
            old_name='date',
            new_name='tarih',
        ),
    ]
