# Generated by Django 3.2.6 on 2021-09-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210917_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorum',
            old_name='name',
            new_name='isim',
        ),
        migrations.RenameField(
            model_name='yorum',
            old_name='body',
            new_name='yorum',
        ),
        migrations.RenameField(
            model_name='yorum',
            old_name='date_added',
            new_name='yorum_tarihi',
        ),
    ]
