# Generated by Django 3.2.6 on 2021-09-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_yorum_anayorum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='anayorum',
        ),
    ]
